# version: "3.8"
  
services:
  dockge:
    image: louislam/dockge:1
    networks: 
      - macvlan-net-1
    restart: unless-stopped
# ports are commented out b/c of the use of macvlan with seperate ip
#    ports:
#      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - /home/donna/stacks:/home/donna/stacks
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=/home/donna/stacks

# macvlan-net-1 created to establish standalone ip (must create this before running docker-compose file)
# docker network create -d macvlan --subnet=10.10.20.0/24 --gateway=10.10.20.1 --ip-range=10.10.20.250/32 -o parent=ens33 macvlan-net-1
networks:
  macvlan-net-1:
    external: true
